### ISSUE TITLE
Cannot post to GHE

### ISSUE THREAD

**Issue by gotson** [tr3buchet/gister#10]
Hi,

i have the following problem when trying to post with the `-p` option to our internal Github Enterprise instance

```
Traceback (most recent call last):
  File "C:\Homeware\Python27\Scripts\gister-script.py", line 9, in <module>
    load_entry_point('gister==1.0.15', 'console_scripts', 'gister')()
  File "C:\Homeware\Python27\lib\site-packages\gister\gister.py", line 180, in create_gist
    headers=headers)
  File "C:\Homeware\Python27\lib\site-packages\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Homeware\Python27\lib\site-packages\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Homeware\Python27\lib\site-packages\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Homeware\Python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Homeware\Python27\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Any idea what could be the problem ?

**Comment by tr3buchet** [comment]
sounds like your GHE deployment doesn't have a proper SSL certificate set up. I'm not sure I want to "fix" gister to allow posting gists anyway. Will your GHE deployment ever have a proper SSL certificate? That's what I would recommend, but since it's sometimes impossible to get whichever department is managing GHE to do it, I can maybe add an option to ignore the host SSL certificate. 

thoughts?

**Comment by gotson** [comment]
Thanks for the insight, will check with them first what they have to say about it :+1:

**Comment by gotson** [comment]
Hi @tr3buchet, i managed to use a .crt file locally together with an environment variable REQUESTS_CA_BUNDLE, but now i get a 404 error.
Any idea what could be the problem ?

```
D:\src>echo toto | gister -p
Traceback (most recent call last):
  File "C:\Homeware\Python27\Scripts\gister-script.py", line 9, in <module>
    load_entry_point('gister==1.0.15', 'console_scripts', 'gister')()
  File "C:\Homeware\Python27\lib\site-packages\gister\gister.py", line 181, in create_gist
    r.raise_for_status()
  File "C:\Homeware\Python27\lib\site-packages\requests\models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
```

**Comment by tr3buchet** [comment]
You'll have to make sure that you can hit the API on your github enterprise deployment. I would try curling it manually just to make sure.

**Comment by gotson** [comment]
It does work well when i use the `--cacert` option of curl to provide the certificate, same certificate i put in `REQUESTS_CA_BUNDLE`

**Comment by tr3buchet** [comment]
When you curl, are you using the `-k` option?

**Comment by gotson** [comment]
No i use only the `--cacert` option:
`D:\src>curl --cacert "P:\Tools\SSH Keys\Unipass\cacerts-1.0.crt"  https://xxxxx/api/v3/`

**Comment by tr3buchet** [comment]
I see what's going on, you guys aren't using a real CA or are perhaps using one requests can't verify. [This](http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification) might be what you need, specifically the part about the `REQUESTS_CA_BUNDLE` environment variable. Sounds like you need to add your CA into the bundle requests uses and/or make a new one and point that environment variable at it. I have no idea how to go about doing this on windows however.
